const UserData = [
  {
    User_ID: 1,
    Join_Date: '2024-05-10',
    Country: 'USA',
    Device_Type: 'Mobile',
    Age: 32,
    Total_Orders: 4,
    'Total_Spent ($)': 245.5,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 7,
    Active_Status: 'Active'
  },
  {
    User_ID: 2,
    Join_Date: '2024-03-22',
    Country: 'Canada',
    Device_Type: 'Desktop',
    Age: 45,
    Total_Orders: 1,
    'Total_Spent ($)': 55.99,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 30,
    Active_Status: 'Inactive'
  },
  {
    User_ID: 3,
    Join_Date: '2023-11-01',
    Country: 'UK',
    Device_Type: 'Tablet',
    Age: 28,
    Total_Orders: 8,
    'Total_Spent ($)': 499.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 3,
    Active_Status: 'Active'
  },
  {
    User_ID: 4,
    Join_Date: '2024-08-15',
    Country: 'USA',
    Device_Type: 'Mobile',
    Age: 19,
    Total_Orders: 0,
    'Total_Spent ($)': 0.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 60,
    Active_Status: 'Inactive'
  },
  {
    User_ID: 5,
    Join_Date: '2023-01-20',
    Country: 'Germany',
    Device_Type: 'Desktop',
    Age: 58,
    Total_Orders: 12,
    'Total_Spent ($)': 1120.3,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 1,
    Active_Status: 'Active'
  },
  {
    User_ID: 6,
    Join_Date: '2024-07-01',
    Country: 'Canada',
    Device_Type: 'Mobile',
    Age: 24,
    Total_Orders: 3,
    'Total_Spent ($)': 150.25,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 14,
    Active_Status: 'Active'
  },
  {
    User_ID: 7,
    Join_Date: '2023-05-18',
    Country: 'UK',
    Device_Type: 'Desktop',
    Age: 39,
    Total_Orders: 5,
    'Total_Spent ($)': 310.75,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 9,
    Active_Status: 'Active'
  },
  {
    User_ID: 8,
    Join_Date: '2024-09-05',
    Country: 'USA',
    Device_Type: 'Mobile',
    Age: 22,
    Total_Orders: 1,
    'Total_Spent ($)': 45.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 2,
    Active_Status: 'Active'
  },
  {
    User_ID: 9,
    Join_Date: '2022-12-01',
    Country: 'Germany',
    Device_Type: 'Tablet',
    Age: 51,
    Total_Orders: 15,
    'Total_Spent ($)': 1500.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 5,
    Active_Status: 'Active'
  },
  {
    User_ID: 10,
    Join_Date: '2024-06-10',
    Country: 'UK',
    Device_Type: 'Desktop',
    Age: 35,
    Total_Orders: 2,
    'Total_Spent ($)': 89.99,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 21,
    Active_Status: 'Active'
  },
  {
    User_ID: 11,
    Join_Date: '2023-03-01',
    Country: 'USA',
    Device_Type: 'Mobile',
    Age: 29,
    Total_Orders: 7,
    'Total_Spent ($)': 420.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 4,
    Active_Status: 'Active'
  },
  {
    User_ID: 12,
    Join_Date: '2024-02-15',
    Country: 'Canada',
    Device_Type: 'Tablet',
    Age: 48,
    Total_Orders: 2,
    'Total_Spent ($)': 110.5,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 18,
    Active_Status: 'Active'
  },
  {
    User_ID: 13,
    Join_Date: '2023-10-25',
    Country: 'Germany',
    Device_Type: 'Desktop',
    Age: 40,
    Total_Orders: 6,
    'Total_Spent ($)': 650.99,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 6,
    Active_Status: 'Active'
  },
  {
    User_ID: 14,
    Join_Date: '2024-01-05',
    Country: 'UK',
    Device_Type: 'Mobile',
    Age: 21,
    Total_Orders: 1,
    'Total_Spent ($)': 35.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 12,
    Active_Status: 'Active'
  },
  {
    User_ID: 15,
    Join_Date: '2022-11-11',
    Country: 'USA',
    Device_Type: 'Desktop',
    Age: 62,
    Total_Orders: 20,
    'Total_Spent ($)': 2500.5,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 1,
    Active_Status: 'Active'
  },
  {
    User_ID: 16,
    Join_Date: '2024-04-01',
    Country: 'Canada',
    Device_Type: 'Mobile',
    Age: 30,
    Total_Orders: 3,
    'Total_Spent ($)': 180.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 15,
    Active_Status: 'Active'
  },
  {
    User_ID: 17,
    Join_Date: '2023-06-20',
    Country: 'Germany',
    Device_Type: 'Tablet',
    Age: 44,
    Total_Orders: 4,
    'Total_Spent ($)': 290.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 10,
    Active_Status: 'Active'
  },
  {
    User_ID: 18,
    Join_Date: '2024-08-01',
    Country: 'UK',
    Device_Type: 'Desktop',
    Age: 25,
    Total_Orders: 0,
    'Total_Spent ($)': 0.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 35,
    Active_Status: 'Inactive'
  },
  {
    User_ID: 19,
    Join_Date: '2023-02-10',
    Country: 'USA',
    Device_Type: 'Mobile',
    Age: 55,
    Total_Orders: 10,
    'Total_Spent ($)': 950.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 8,
    Active_Status: 'Active'
  },
  {
    User_ID: 20,
    Join_Date: '2024-05-22',
    Country: 'Canada',
    Device_Type: 'Desktop',
    Age: 38,
    Total_Orders: 2,
    'Total_Spent ($)': 75.5,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 25,
    Active_Status: 'Active'
  },
  {
    User_ID: 21,
    Join_Date: '2023-07-07',
    Country: 'UK',
    Device_Type: 'Mobile',
    Age: 27,
    Total_Orders: 6,
    'Total_Spent ($)': 380.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 2,
    Active_Status: 'Active'
  },
  {
    User_ID: 22,
    Join_Date: '2024-09-10',
    Country: 'Germany',
    Device_Type: 'Mobile',
    Age: 18,
    Total_Orders: 0,
    'Total_Spent ($)': 0.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 45,
    Active_Status: 'Inactive'
  },
  {
    User_ID: 23,
    Join_Date: '2023-04-15',
    Country: 'USA',
    Device_Type: 'Tablet',
    Age: 41,
    Total_Orders: 9,
    'Total_Spent ($)': 780.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 5,
    Active_Status: 'Active'
  },
  {
    User_ID: 24,
    Join_Date: '2024-01-28',
    Country: 'Canada',
    Device_Type: 'Desktop',
    Age: 50,
    Total_Orders: 3,
    'Total_Spent ($)': 199.99,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 16,
    Active_Status: 'Active'
  },
  {
    User_ID: 25,
    Join_Date: '2022-10-01',
    Country: 'UK',
    Device_Type: 'Mobile',
    Age: 65,
    Total_Orders: 25,
    'Total_Spent ($)': 3100.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 3,
    Active_Status: 'Active'
  },
  {
    User_ID: 26,
    Join_Date: '2024-03-10',
    Country: 'Germany',
    Device_Type: 'Mobile',
    Age: 23,
    Total_Orders: 1,
    'Total_Spent ($)': 49.99,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 28,
    Active_Status: 'Active'
  },
  {
    User_ID: 27,
    Join_Date: '2023-08-05',
    Country: 'USA',
    Device_Type: 'Desktop',
    Age: 33,
    Total_Orders: 5,
    'Total_Spent ($)': 350.5,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 11,
    Active_Status: 'Active'
  },
  {
    User_ID: 28,
    Join_Date: '2024-06-25',
    Country: 'Canada',
    Device_Type: 'Tablet',
    Age: 42,
    Total_Orders: 2,
    'Total_Spent ($)': 130.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 20,
    Active_Status: 'Active'
  },
  {
    User_ID: 29,
    Join_Date: '2023-01-01',
    Country: 'UK',
    Device_Type: 'Mobile',
    Age: 59,
    Total_Orders: 14,
    'Total_Spent ($)': 1300.75,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 7,
    Active_Status: 'Active'
  },
  {
    User_ID: 30,
    Join_Date: '2024-07-15',
    Country: 'Germany',
    Device_Type: 'Desktop',
    Age: 31,
    Total_Orders: 1,
    'Total_Spent ($)': 65.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 13,
    Active_Status: 'Active'
  },
  {
    User_ID: 31,
    Join_Date: '2023-05-01',
    Country: 'USA',
    Device_Type: 'Mobile',
    Age: 26,
    Total_Orders: 4,
    'Total_Spent ($)': 270.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 9,
    Active_Status: 'Active'
  },
  {
    User_ID: 32,
    Join_Date: '2024-02-01',
    Country: 'Canada',
    Device_Type: 'Desktop',
    Age: 47,
    Total_Orders: 3,
    'Total_Spent ($)': 175.5,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 22,
    Active_Status: 'Active'
  },
  {
    User_ID: 33,
    Join_Date: '2023-11-20',
    Country: 'UK',
    Device_Type: 'Tablet',
    Age: 40,
    Total_Orders: 7,
    'Total_Spent ($)': 510.99,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 4,
    Active_Status: 'Active'
  },
  {
    User_ID: 34,
    Join_Date: '2024-08-28',
    Country: 'Germany',
    Device_Type: 'Mobile',
    Age: 20,
    Total_Orders: 0,
    'Total_Spent ($)': 0.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 50,
    Active_Status: 'Inactive'
  },
  {
    User_ID: 35,
    Join_Date: '2022-12-25',
    Country: 'USA',
    Device_Type: 'Desktop',
    Age: 53,
    Total_Orders: 18,
    'Total_Spent ($)': 2100.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 1,
    Active_Status: 'Active'
  },
  {
    User_ID: 36,
    Join_Date: '2024-04-10',
    Country: 'Canada',
    Device_Type: 'Mobile',
    Age: 34,
    Total_Orders: 3,
    'Total_Spent ($)': 190.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 17,
    Active_Status: 'Active'
  },
  {
    User_ID: 37,
    Join_Date: '2023-06-05',
    Country: 'UK',
    Device_Type: 'Tablet',
    Age: 46,
    Total_Orders: 5,
    'Total_Spent ($)': 340.5,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 8,
    Active_Status: 'Active'
  },
  {
    User_ID: 38,
    Join_Date: '2024-09-15',
    Country: 'USA',
    Device_Type: 'Desktop',
    Age: 23,
    Total_Orders: 1,
    'Total_Spent ($)': 55.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 3,
    Active_Status: 'Active'
  },
  {
    User_ID: 39,
    Join_Date: '2022-11-05',
    Country: 'Germany',
    Device_Type: 'Mobile',
    Age: 60,
    Total_Orders: 22,
    'Total_Spent ($)': 2800.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 6,
    Active_Status: 'Active'
  },
  {
    User_ID: 40,
    Join_Date: '2024-06-01',
    Country: 'Canada',
    Device_Type: 'Desktop',
    Age: 37,
    Total_Orders: 2,
    'Total_Spent ($)': 99.99,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 26,
    Active_Status: 'Active'
  },
  {
    User_ID: 41,
    Join_Date: '2023-03-15',
    Country: 'UK',
    Device_Type: 'Mobile',
    Age: 29,
    Total_Orders: 6,
    'Total_Spent ($)': 410.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 10,
    Active_Status: 'Active'
  },
  {
    User_ID: 42,
    Join_Date: '2024-01-10',
    Country: 'Germany',
    Device_Type: 'Tablet',
    Age: 49,
    Total_Orders: 2,
    'Total_Spent ($)': 120.5,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 19,
    Active_Status: 'Active'
  },
  {
    User_ID: 43,
    Join_Date: '2023-10-10',
    Country: 'USA',
    Device_Type: 'Desktop',
    Age: 36,
    Total_Orders: 8,
    'Total_Spent ($)': 710.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 5,
    Active_Status: 'Active'
  },
  {
    User_ID: 44,
    Join_Date: '2024-05-05',
    Country: 'Canada',
    Device_Type: 'Mobile',
    Age: 27,
    Total_Orders: 3,
    'Total_Spent ($)': 160.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 14,
    Active_Status: 'Active'
  },
  {
    User_ID: 45,
    Join_Date: '2022-10-20',
    Country: 'UK',
    Device_Type: 'Desktop',
    Age: 56,
    Total_Orders: 16,
    'Total_Spent ($)': 1750.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 2,
    Active_Status: 'Active'
  },
  {
    User_ID: 46,
    Join_Date: '2024-03-25',
    Country: 'Germany',
    Device_Type: 'Mobile',
    Age: 32,
    Total_Orders: 1,
    'Total_Spent ($)': 59.99,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 32,
    Active_Status: 'Inactive'
  },
  {
    User_ID: 47,
    Join_Date: '2023-07-20',
    Country: 'USA',
    Device_Type: 'Tablet',
    Age: 43,
    Total_Orders: 5,
    'Total_Spent ($)': 390.5,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 12,
    Active_Status: 'Active'
  },
  {
    User_ID: 48,
    Join_Date: '2024-08-05',
    Country: 'Canada',
    Device_Type: 'Desktop',
    Age: 21,
    Total_Orders: 0,
    'Total_Spent ($)': 0.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 40,
    Active_Status: 'Inactive'
  },
  {
    User_ID: 49,
    Join_Date: '2023-02-25',
    Country: 'UK',
    Device_Type: 'Mobile',
    Age: 54,
    Total_Orders: 11,
    'Total_Spent ($)': 1050.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 9,
    Active_Status: 'Active'
  },
  {
    User_ID: 50,
    Join_Date: '2024-05-15',
    Country: 'Germany',
    Device_Type: 'Desktop',
    Age: 39,
    Total_Orders: 2,
    'Total_Spent ($)': 85.5,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 23,
    Active_Status: 'Active'
  },
  {
    User_ID: 51,
    Join_Date: '2023-04-01',
    Country: 'USA',
    Device_Type: 'Mobile',
    Age: 28,
    Total_Orders: 5,
    'Total_Spent ($)': 300.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 6,
    Active_Status: 'Active'
  },
  {
    User_ID: 52,
    Join_Date: '2024-02-20',
    Country: 'Canada',
    Device_Type: 'Desktop',
    Age: 46,
    Total_Orders: 3,
    'Total_Spent ($)': 185.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 24,
    Active_Status: 'Active'
  },
  {
    User_ID: 53,
    Join_Date: '2023-12-01',
    Country: 'UK',
    Device_Type: 'Tablet',
    Age: 30,
    Total_Orders: 7,
    'Total_Spent ($)': 550.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 1,
    Active_Status: 'Active'
  },
  {
    User_ID: 54,
    Join_Date: '2024-07-25',
    Country: 'Germany',
    Device_Type: 'Mobile',
    Age: 19,
    Total_Orders: 0,
    'Total_Spent ($)': 0.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 55,
    Active_Status: 'Inactive'
  },
  {
    User_ID: 55,
    Join_Date: '2022-11-20',
    Country: 'USA',
    Device_Type: 'Desktop',
    Age: 61,
    Total_Orders: 21,
    'Total_Spent ($)': 2600.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 4,
    Active_Status: 'Active'
  },
  {
    User_ID: 56,
    Join_Date: '2024-04-20',
    Country: 'Canada',
    Device_Type: 'Mobile',
    Age: 33,
    Total_Orders: 4,
    'Total_Spent ($)': 220.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 13,
    Active_Status: 'Active'
  },
  {
    User_ID: 57,
    Join_Date: '2023-06-15',
    Country: 'UK',
    Device_Type: 'Tablet',
    Age: 47,
    Total_Orders: 6,
    'Total_Spent ($)': 450.99,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 7,
    Active_Status: 'Active'
  },
  {
    User_ID: 58,
    Join_Date: '2024-09-01',
    Country: 'USA',
    Device_Type: 'Desktop',
    Age: 26,
    Total_Orders: 1,
    'Total_Spent ($)': 60.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 1,
    Active_Status: 'Active'
  },
  {
    User_ID: 59,
    Join_Date: '2022-10-10',
    Country: 'Germany',
    Device_Type: 'Mobile',
    Age: 63,
    Total_Orders: 28,
    'Total_Spent ($)': 3500.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 8,
    Active_Status: 'Active'
  },
  {
    User_ID: 60,
    Join_Date: '2024-06-20',
    Country: 'Canada',
    Device_Type: 'Desktop',
    Age: 36,
    Total_Orders: 2,
    'Total_Spent ($)': 115.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 27,
    Active_Status: 'Active'
  },
  {
    User_ID: 61,
    Join_Date: '2023-03-30',
    Country: 'USA',
    Device_Type: 'Mobile',
    Age: 25,
    Total_Orders: 4,
    'Total_Spent ($)': 280.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 11,
    Active_Status: 'Active'
  },
  {
    User_ID: 62,
    Join_Date: '2024-01-20',
    Country: 'UK',
    Device_Type: 'Tablet',
    Age: 48,
    Total_Orders: 3,
    'Total_Spent ($)': 150.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 20,
    Active_Status: 'Active'
  },
  {
    User_ID: 63,
    Join_Date: '2023-11-10',
    Country: 'Germany',
    Device_Type: 'Desktop',
    Age: 41,
    Total_Orders: 9,
    'Total_Spent ($)': 810.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 3,
    Active_Status: 'Active'
  },
  {
    User_ID: 64,
    Join_Date: '2024-08-10',
    Country: 'USA',
    Device_Type: 'Mobile',
    Age: 22,
    Total_Orders: 1,
    'Total_Spent ($)': 40.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 38,
    Active_Status: 'Inactive'
  },
  {
    User_ID: 65,
    Join_Date: '2022-12-15',
    Country: 'Canada',
    Device_Type: 'Desktop',
    Age: 57,
    Total_Orders: 17,
    'Total_Spent ($)': 1900.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 5,
    Active_Status: 'Active'
  },
  {
    User_ID: 66,
    Join_Date: '2024-04-25',
    Country: 'UK',
    Device_Type: 'Mobile',
    Age: 31,
    Total_Orders: 3,
    'Total_Spent ($)': 170.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 16,
    Active_Status: 'Active'
  },
  {
    User_ID: 67,
    Join_Date: '2023-05-25',
    Country: 'Germany',
    Device_Type: 'Tablet',
    Age: 45,
    Total_Orders: 5,
    'Total_Spent ($)': 320.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 10,
    Active_Status: 'Active'
  },
  {
    User_ID: 68,
    Join_Date: '2024-09-20',
    Country: 'USA',
    Device_Type: 'Desktop',
    Age: 24,
    Total_Orders: 0,
    'Total_Spent ($)': 0.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 48,
    Active_Status: 'Inactive'
  },
  {
    User_ID: 69,
    Join_Date: '2023-02-01',
    Country: 'Canada',
    Device_Type: 'Mobile',
    Age: 56,
    Total_Orders: 13,
    'Total_Spent ($)': 1200.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 12,
    Active_Status: 'Active'
  },
  {
    User_ID: 70,
    Join_Date: '2024-05-28',
    Country: 'UK',
    Device_Type: 'Desktop',
    Age: 37,
    Total_Orders: 2,
    'Total_Spent ($)': 95.5,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 29,
    Active_Status: 'Active'
  },
  {
    User_ID: 71,
    Join_Date: '2023-07-15',
    Country: 'USA',
    Device_Type: 'Mobile',
    Age: 29,
    Total_Orders: 6,
    'Total_Spent ($)': 400.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 2,
    Active_Status: 'Active'
  },
  {
    User_ID: 72,
    Join_Date: '2024-01-01',
    Country: 'Germany',
    Device_Type: 'Tablet',
    Age: 40,
    Total_Orders: 2,
    'Total_Spent ($)': 135.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 15,
    Active_Status: 'Active'
  },
  {
    User_ID: 73,
    Join_Date: '2023-04-20',
    Country: 'Canada',
    Device_Type: 'Desktop',
    Age: 43,
    Total_Orders: 8,
    'Total_Spent ($)': 690.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 4,
    Active_Status: 'Active'
  },
  {
    User_ID: 74,
    Join_Date: '2024-08-20',
    Country: 'UK',
    Device_Type: 'Mobile',
    Age: 20,
    Total_Orders: 1,
    'Total_Spent ($)': 30.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 33,
    Active_Status: 'Inactive'
  },
  {
    User_ID: 75,
    Join_Date: '2022-10-25',
    Country: 'USA',
    Device_Type: 'Desktop',
    Age: 64,
    Total_Orders: 23,
    'Total_Spent ($)': 2900.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 6,
    Active_Status: 'Active'
  },
  {
    User_ID: 76,
    Join_Date: '2024-03-05',
    Country: 'Germany',
    Device_Type: 'Mobile',
    Age: 35,
    Total_Orders: 1,
    'Total_Spent ($)': 55.99,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 31,
    Active_Status: 'Inactive'
  },
  {
    User_ID: 77,
    Join_Date: '2023-08-15',
    Country: 'Canada',
    Device_Type: 'Tablet',
    Age: 38,
    Total_Orders: 5,
    'Total_Spent ($)': 370.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 8,
    Active_Status: 'Active'
  },
  {
    User_ID: 78,
    Join_Date: '2024-06-30',
    Country: 'UK',
    Device_Type: 'Desktop',
    Age: 49,
    Total_Orders: 2,
    'Total_Spent ($)': 125.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 19,
    Active_Status: 'Active'
  },
  {
    User_ID: 79,
    Join_Date: '2023-01-25',
    Country: 'Germany',
    Device_Type: 'Mobile',
    Age: 52,
    Total_Orders: 10,
    'Total_Spent ($)': 990.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 7,
    Active_Status: 'Active'
  },
  {
    User_ID: 80,
    Join_Date: '2024-07-10',
    Country: 'USA',
    Device_Type: 'Desktop',
    Age: 30,
    Total_Orders: 1,
    'Total_Spent ($)': 70.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 25,
    Active_Status: 'Active'
  },
  {
    User_ID: 81,
    Join_Date: '2023-05-10',
    Country: 'Canada',
    Device_Type: 'Mobile',
    Age: 27,
    Total_Orders: 4,
    'Total_Spent ($)': 260.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 9,
    Active_Status: 'Active'
  },
  {
    User_ID: 82,
    Join_Date: '2024-02-25',
    Country: 'UK',
    Device_Type: 'Desktop',
    Age: 44,
    Total_Orders: 3,
    'Total_Spent ($)': 165.5,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 23,
    Active_Status: 'Active'
  },
  {
    User_ID: 83,
    Join_Date: '2023-10-05',
    Country: 'USA',
    Device_Type: 'Tablet',
    Age: 34,
    Total_Orders: 7,
    'Total_Spent ($)': 590.99,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 5,
    Active_Status: 'Active'
  },
  {
    User_ID: 84,
    Join_Date: '2024-09-25',
    Country: 'Germany',
    Device_Type: 'Mobile',
    Age: 21,
    Total_Orders: 0,
    'Total_Spent ($)': 0.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 58,
    Active_Status: 'Inactive'
  },
  {
    User_ID: 85,
    Join_Date: '2022-12-30',
    Country: 'Canada',
    Device_Type: 'Desktop',
    Age: 59,
    Total_Orders: 19,
    'Total_Spent ($)': 2300.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 1,
    Active_Status: 'Active'
  },
  {
    User_ID: 86,
    Join_Date: '2024-04-05',
    Country: 'UK',
    Device_Type: 'Mobile',
    Age: 32,
    Total_Orders: 4,
    'Total_Spent ($)': 210.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 18,
    Active_Status: 'Active'
  },
  {
    User_ID: 87,
    Join_Date: '2023-06-25',
    Country: 'USA',
    Device_Type: 'Tablet',
    Age: 40,
    Total_Orders: 5,
    'Total_Spent ($)': 360.5,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 10,
    Active_Status: 'Active'
  },
  {
    User_ID: 88,
    Join_Date: '2024-08-08',
    Country: 'Germany',
    Device_Type: 'Desktop',
    Age: 25,
    Total_Orders: 1,
    'Total_Spent ($)': 45.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 36,
    Active_Status: 'Inactive'
  },
  {
    User_ID: 89,
    Join_Date: '2023-02-15',
    Country: 'Canada',
    Device_Type: 'Mobile',
    Age: 53,
    Total_Orders: 11,
    'Total_Spent ($)': 1150.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 14,
    Active_Status: 'Active'
  },
  {
    User_ID: 90,
    Join_Date: '2024-05-01',
    Country: 'UK',
    Device_Type: 'Desktop',
    Age: 38,
    Total_Orders: 2,
    'Total_Spent ($)': 89.99,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 30,
    Active_Status: 'Inactive'
  },
  {
    User_ID: 91,
    Join_Date: '2023-07-01',
    Country: 'Germany',
    Device_Type: 'Mobile',
    Age: 28,
    Total_Orders: 5,
    'Total_Spent ($)': 350.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 3,
    Active_Status: 'Active'
  },
  {
    User_ID: 92,
    Join_Date: '2024-01-15',
    Country: 'USA',
    Device_Type: 'Tablet',
    Age: 47,
    Total_Orders: 3,
    'Total_Spent ($)': 170.5,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 17,
    Active_Status: 'Active'
  },
  {
    User_ID: 93,
    Join_Date: '2023-04-05',
    Country: 'UK',
    Device_Type: 'Desktop',
    Age: 42,
    Total_Orders: 8,
    'Total_Spent ($)': 750.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 6,
    Active_Status: 'Active'
  },
  {
    User_ID: 94,
    Join_Date: '2024-08-01',
    Country: 'Canada',
    Device_Type: 'Mobile',
    Age: 23,
    Total_Orders: 1,
    'Total_Spent ($)': 50.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 42,
    Active_Status: 'Inactive'
  },
  {
    User_ID: 95,
    Join_Date: '2022-10-05',
    Country: 'Germany',
    Device_Type: 'Desktop',
    Age: 66,
    Total_Orders: 30,
    'Total_Spent ($)': 3900.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 2,
    Active_Status: 'Active'
  },
  {
    User_ID: 96,
    Join_Date: '2024-03-15',
    Country: 'USA',
    Device_Type: 'Mobile',
    Age: 36,
    Total_Orders: 2,
    'Total_Spent ($)': 105.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 27,
    Active_Status: 'Active'
  },
  {
    User_ID: 97,
    Join_Date: '2023-08-25',
    Country: 'UK',
    Device_Type: 'Tablet',
    Age: 39,
    Total_Orders: 6,
    'Total_Spent ($)': 420.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 9,
    Active_Status: 'Active'
  },
  {
    User_ID: 98,
    Join_Date: '2024-06-05',
    Country: 'Germany',
    Device_Type: 'Desktop',
    Age: 50,
    Total_Orders: 3,
    'Total_Spent ($)': 180.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 21,
    Active_Status: 'Active'
  },
  {
    User_ID: 99,
    Join_Date: '2023-01-10',
    Country: 'Canada',
    Device_Type: 'Mobile',
    Age: 54,
    Total_Orders: 12,
    'Total_Spent ($)': 1100.0,
    Is_Subscribed: true,
    Last_Login_Days_Ago: 5,
    Active_Status: 'Active'
  },
  {
    User_ID: 100,
    Join_Date: '2024-07-20',
    Country: 'USA',
    Device_Type: 'Desktop',
    Age: 31,
    Total_Orders: 1,
    'Total_Spent ($)': 65.0,
    Is_Subscribed: false,
    Last_Login_Days_Ago: 24,
    Active_Status: 'Active'
  }
]

export default UserData
